[package]
name = "m21-containerization-solution"
description = "Reference solution for 21-containerization"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
axum.workspace = true
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_yaml_ng.workspace = true
