[package]
name = "m37-wasm"
description = "YOUR WORKSPACE for 37-wasm"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

# cdylib: what wasm-pack turns into a .wasm module; rlib: for native tests.
[lib]
doctest = false
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen.workspace = true
