#!/usr/bin/env python3
"""Scaffold exercise/ and tests/ for a module whose solution/ is written.

Usage (from the repository root):
    python3 tools/scaffold.py <module_dir> <package_prefix> <display name>
    python3 tools/scaffold.py 02-intermediate-rust/07-collections-iterators m07-collections-iterators 07-collections-iterators

Creates, without overwriting existing files (set FORCE=1 to overwrite):
  exercise/Cargo.toml   copied from solution/, renamed, `[lib] doctest = false`
  exercise/src/lib.rs   the solution's module list under a "YOUR WORKSPACE" header
  exercise/src/main.rs  the solution's runner, with crate names swapped
  exercise/src/*.rs     skeletons generated by skeleton.py
  tests/Cargo.toml      depends on both crates; feature `mine` selects the exercise
  tests/src/lib.rs      `pub use <crate> as sut;` switched by `mine`
You still write tests/src/exercises.rs, and review the skeletons by hand
(see CLAUDE.md, "Skeleton gotchas").
"""
import os
import re
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))

mod_dir, pkg, display = sys.argv[1:4]
sol_pkg = f'{pkg}-solution'
tests_pkg = f'{pkg}-tests'
crate = pkg.replace('-', '_')
sol_crate = sol_pkg.replace('-', '_')
num = pkg[1:3]

sol = os.path.join(mod_dir, 'solution')
ex = os.path.join(mod_dir, 'exercise')
tests = os.path.join(mod_dir, 'tests')
os.makedirs(os.path.join(ex, 'src'), exist_ok=True)
os.makedirs(os.path.join(tests, 'src'), exist_ok=True)


def write_if_absent(path, text):
    if os.path.exists(path) and os.environ.get('FORCE') != '1':
        print('skip (exists):', path)
        return
    open(path, 'w').write(text)
    print('wrote', path)


# ---- exercise/Cargo.toml: copy solution's, rename, disable doctests ----------
cargo = open(os.path.join(sol, 'Cargo.toml')).read()
cargo = cargo.replace(f'name = "{sol_pkg}"', f'name = "{pkg}"')
cargo = re.sub(r'description = ".*"', f'description = "YOUR WORKSPACE for {display}"', cargo)
cargo = re.sub(r'\n# .*build.rs.*\nbuild = "build.rs"\n', '\n', cargo)
cargo = cargo.replace(sol_crate, crate).replace(sol_pkg, pkg)
# a proc-macro companion crate: point at the exercise one if present
cargo = cargo.replace('-derive-solution', '-derive')
# [lib] doctest = false -- doc examples would hit todo!() and fail `cargo test`
if '[lib]' in cargo:
    cargo = cargo.replace('[lib]', '[lib]\ndoctest = false', 1)
else:
    cargo = re.sub(r'(publish\.workspace = true\n)', r'\1\n# Doc examples would run against todo!() bodies, so they are off here.\n[lib]\ndoctest = false\n', cargo, count=1)
# drop [[bench]] sections and lints (the learner adds lints themselves when asked)
write_if_absent(os.path.join(ex, 'Cargo.toml'), cargo)

# ---- exercise/src/lib.rs -----------------------------------------------------
lib = open(os.path.join(sol, 'src', 'lib.rs')).read()
lines = lib.split('\n')
body_start = 0
while body_start < len(lines) and lines[body_start].startswith('//!'):
    body_start += 1
header = f'''//! Module {num} -- {display}. YOUR WORKSPACE.
//!
//! Each `exNN_*.rs` file has the signatures the tests expect, with `todo!()`
//! bodies. Replace each `todo!()` with your implementation, then:
//!
//!     cargo run  -p {pkg} -- <exercise number>
//!     cargo test -p {tests_pkg} --features mine
//!
//! Stuck? Compare with ../solution/src -- same file and function names.

// Remove this line once you have started: it silences "unused" warnings
// while everything is still todo!().
#![allow(unused)]
'''
rest = '\n'.join(lines[body_start:]).replace(sol_crate, crate)
write_if_absent(os.path.join(ex, 'src', 'lib.rs'), header + rest)

# ---- exercise/src/main.rs ----------------------------------------------------
main_path = os.path.join(sol, 'src', 'main.rs')
if os.path.exists(main_path):
    main = open(main_path).read()
    main = main.replace(sol_crate, crate).replace(sol_pkg, pkg)
    main = main.replace(f'// Reference solution for {display}.',
                        f'// {display} -- YOUR WORKSPACE.\n//\n// This runner is ready to use: it calls the functions in src/ that you\n// fill in. Until you implement a part it stops with "not yet implemented".')
    main = main.replace('-- reference solution', '-- your workspace')
    write_if_absent(os.path.join(ex, 'src', 'main.rs'), main)

# ---- other source files ------------------------------------------------------
subprocess.run([sys.executable, os.path.join(HERE, 'skeleton.py'),
                os.path.join(sol, 'src'), os.path.join(ex, 'src'), sol_crate, crate], check=True)

# ---- tests/ ------------------------------------------------------------------
write_if_absent(os.path.join(tests, 'Cargo.toml'), f'''[package]
name = "{tests_pkg}"
description = "Tests for {display} -- run against the solution or your own code"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[features]
# cargo test -p {tests_pkg}                   -> tests ../solution
# cargo test -p {tests_pkg} --features mine   -> tests ../exercise (your code)
mine = []

[dependencies]
{pkg} = {{ path = "../exercise" }}
{sol_pkg} = {{ path = "../solution" }}
''')
write_if_absent(os.path.join(tests, 'src', 'lib.rs'), f'''//! Tests for {display}.
//!
//! `sut` ("system under test") is either the reference solution or your own
//! exercise crate, chosen by the `mine` feature. Every test is written against
//! `sut`, so the same tests check both.

#[cfg(not(feature = "mine"))]
pub use {sol_crate} as sut;

#[cfg(feature = "mine")]
pub use {crate} as sut;

#[cfg(test)]
mod exercises;
''')
